name: airtable
on:
  issue_comment:
    types: [created]
  schedule:
    - cron: "00 00 * * *"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Install cloudinary-cli
        run: |
          python -m pip install --upgrade pip
          pip install cloudinary-cli
          
      - name: Install deps
        run: make install
      
      - name: Create and upload invoices
        run: make start cl-url=${{ secrets.CL_URL }} token=${{ secrets.AIRTABLE_TOKEN }}
